### ISSUE TITLE
About the pre-trained weights of the debit_base.pth

### ISSUE THREAD

**Issue by Andy-zd** [naver/debit#1]
Hi,

Thanks for your great work! I am trying to train 3rd phase of the RL policy learning, but I got the error message 'FileNotFoundError: [Errno 2] No such file or directory: 'weights/nle/checkpoints/croco-rpve/debit_base.pth'. Could you please release the pre-trained weights?

Thanks for your time and consideration.

**Comment by WGW101** [comment]
Hi Andy,

Thank you for checking out our work, hope you will find it useful.

As (poorly) indicated in the last section of the [readme](https://github.com/naver/debit#training-3rd-phase), because the weights of the binocular encoder are frozen during the 3rd training phase, the pre-trained weights can be extracted from the final weights using the [scripts/extract_pretrained_croco_rpve.py](https://github.com/naver/debit/blob/main/scripts/extract_pretrained_croco_rpve.py):
```bash
python scripts/extract_pretrained_croco_rpve.py -K path/to/downloaded/ckpt.pth -o desired/path/to/pre-trained/weights.pth
```
by default targeting DEBiT-B checkpoint, and creating a new `.pth` file for the pre-trained weights at the path the error points to.

You will of course need to download the final weights of the variant of your choice for it to work.
I will try to improve the readme and provide explanations alongside the command example next time I have the chance to update the repo.

Let me know if you are able to start your own training, and if I can be of further assistance, otherwise I'll close the issue in a few days.

**Comment by Andy-zd** [comment]
Thanks for your reply. It is good for me.
